#!/bin/bash

# Get the C file name from the $CFILE variable
c_file="$CFILE"

# Generate the output file name by replacing the .c extension with .s
output_file="${c_file%.c}.s"

# Compile the C code and generate the assembly code
gcc -S -masm=intel "$c_file" -o "$output_file"
